### ISSUE TITLE
bug: notify developer of invalid API key on the web

### ISSUE THREAD

**Issue by csells** [csells/flutter_ai_toolkit#39]
On the web, it just hangs (bad).
<img width="200" src="https://github.com/user-attachments/assets/e3ea273e-4a10-4c75-9c2c-2ea51326d914"

On desktop, there's an error message (good):
<img width="200" src="https://github.com/user-attachments/assets/9548ddc1-70f8-4fc1-9c8f-1408f3dfa321">

On iOS, there's an error message (good):
<img width="200" src="https://github.com/user-attachments/assets/8858303a-021c-445f-b857-d7d9d9ed975e">

On Android, there's an error message (good):
<img width="200" src="https://github.com/user-attachments/assets/eb42764d-2015-4e36-a359-c530301a5d61">

Combine this bug with [this bug](https://github.com/csells/flutter_ai_toolkit/issues/18) and it looks like a problem with error handle on the web.

**Comment by csells** [comment]
OK. I've tracked this down to typical usage in the Flutter AI Toolkit implementation of the LLM providers, e.g. [in the `GeminiProvider`](https://github.com/csells/flutter_ai_toolkit/blob/main/lib/src/providers/implementations/gemini_provider.dart#L75C5-L75C14):

```dart
    final response = contentStreamGenerator(content);
    await for (final chunk in response) {
      final text = chunk.text;
      if (text != null) yield text;
    }
  }
```

On not web, if there's an exception in `contentStreamGenerator`, then the exception propagates to the `listen` call upstream and it's reported to the user. On the web, however, things just hang, which is a known Dart bug: https://github.com/flutter/flutter/issues/108866 (which is a closed dupe of still very open https://github.com/dart-lang/sdk/issues/47764, but I don't know what `DDC` is and I do know what `Web` is, so...).

I can't use `listen`, since this is a single-subscriber stream and upstream needs to call `listen` (which can only be called once on a single-subscriber stream).

I can't use `stream.forEach(processEach)` because I can't call `yield` instead the `processEach` function (even if it's a closure) and the upstream needs the responses as they come in (so give that cool LLM streaming response effect).

So I'm happy to rewrite all my `await for` calls to work around this bug, but I have no idea how to rewrite them. And since the samples are going to be run in Debug and not Release mode, having the code correctly report errors in Debug mode is pretty important.

@munificent @kevmoo @khanhnwin thoughts?

**Comment by kevmoo** [comment]
DDC is the dev compiler. It's what runs when you do `flutter run web -d chrome`.

**Comment by csells** [comment]
@kevmoo was nice enough to grab a quick GVC with me and help me rewrite the code w/o `await for` as a work-around, which cleared up this bug and helped clear up another one (it turns out that exceptions are a pretty handy wait to help track down bugs -- who knew??).

I dropped the work around details into the original bug, which will hopefully be fixed one day but is no longer blocking the AI Toolkit: https://github.com/dart-lang/sdk/issues/47764#issuecomment-2495726000

Thanks, Kev!
