### ISSUE TITLE
bug: Long pressing a message and then clicking outside of the toolbar should make the toolbar disappear

### ISSUE THREAD

**Issue by csells** [csells/flutter_ai_toolkit#47]
Shouldn’t require that I click “X”

![image8](https://github.com/user-attachments/assets/7afda6dd-2826-4085-bdba-5369805432ee)

**Comment by Shashwat-111** [comment]
I feel this long press is not very user friendly for desktop/web.
How about something like this for desktop ?
![image](https://github.com/user-attachments/assets/7e9cc0ff-a29b-492a-9320-75f5a66a0747)
the repeat button can may be regenerate the response.

Let me know what you think.

**Comment by csells** [comment]
Let's have this discussion on the [appropriate bug](https://github.com/csells/flutter_ai_toolkit/issues/12). but yes, that's the UX we should have for web/desktop. It should be triggered by hover and should not affect the layout, i.e. those buttons should be in a Stack.
