### ISSUE TITLE
TextField overflow error for large inputs

### ISSUE THREAD

**Issue by Shashwat-111** [csells/flutter_ai_toolkit#55]
![OverflowError_Ai_toolkit](https://github.com/user-attachments/assets/8481facc-5482-4665-88a0-bcb4e10d90b5)

**Comment by csells** [comment]
wrapped text field in `SingleChildScrollView`:
<img width="912" alt="image" src="https://github.com/user-attachments/assets/844ceadf-42e3-4df8-a9ab-97f08260e088">
