### ISSUE TITLE
Cookbook Article for docs.flutter.dev/cookbook

### ISSUE THREAD

**Issue by khanhnwin** [csells/flutter_ai_toolkit#57]
Add an article to the [Flutter Cookbook](https://docs.flutter.dev/cookbook) to cover at least the following:

- [ ] Guidance to build your own LlmProvider & sample code, ensuring that there are copy/paste-able snippets to make it easy to get getting building your own

- [ ] document UX features

- [ ] document samples (https://github.com/csells/flutter_ai_toolkit/issues/42)

**Comment by csells** [comment]
fixed
