### ISSUE TITLE
Remove Flutter build files

### ISSUE THREAD

**Issue by loic-sharma** [csells/flutter_ai_toolkit#75]
FYI, the following files should not be checked into version control:

https://github.com/csells/flutter_ai_toolkit/blob/main/.flutter-plugins
https://github.com/csells/flutter_ai_toolkit/blob/main/.flutter-plugins-dependencies

**Comment by csells** [comment]
I can easily do that, @loic-sharma . my question is: how do you know I'm not supposed to check in those files? Can you point me at the docs for my own education? Thanks.

**Comment by loic-sharma** [comment]
I'm not aware of any docs on these files, other than engineering designs. However, the default `.gitignore` ignores these files:

https://github.com/flutter/flutter/blob/bf1fac785e79c53e0bb55261f8b96fb82eb914a8/packages/flutter_tools/templates/app_shared/.gitignore.tmpl#L30-L31

Also both of these files recommend you not to check them in:

https://github.com/csells/flutter_ai_toolkit/blob/2ad61c9735d9a3ef52d19e631ea80ebbc9547083/.flutter-plugins#L1

https://github.com/csells/flutter_ai_toolkit/blob/2ad61c9735d9a3ef52d19e631ea80ebbc9547083/.flutter-plugins-dependencies#L1

This file format isn't stable. We might make breaking changes to these file across minor Flutter SDK releases. In fact, we're planning on removing `.flutter-plugins` entirely.

**Comment by csells** [comment]
thanks. I didn't futz with the default `.gitignore` on purpose. I'll remove them.
